server {
    listen 80 default_server;
    server_name _;

    location = /up {
        access_log off;
        return 200 "OK";
    }

    location / {
        proxy_pass http://localhost:3000;

        # Optional recommended proxy headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}