default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: "postgresql://postgres:secret@pg:5432/callcapture_development"

production:
  primary:
    <<: *default
    url: "postgresql://postgres:strong-password@callcapture-db:5432/callcapture_production"

  queue:
    <<: *default
    url: "postgresql://postgres:strong-password@callcapture-db:5432/callcapture_queue"

  cable:
    <<: *default
    url: "postgresql://postgres:strong-password@callcapture-db:5432/callcapture_cable"

  cache:
    <<: *default
    url: "postgresql://postgres:strong-password@callcapture-db:5432/callcapture_cache"