default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

production:
  <<: *default
  primary:
    url: "postgresql://postgres:postgres@callcapture-db:5432/callcapture_production"

  queue:
    url: "postgresql://postgres:postgres@callcapture-db:5432/callcapture_queue"

  cable:
    url: postgresql://postgres:postgres@callcapture-db:5432/callcapture_cable"

  cache:
    url: postgresql://postgres:postgres@callcapture-db:5432/callcapture_cache"