service: callcapture

image: sgalbur128/callcapture

servers:
  web:
    - 107.170.15.86

proxy:
  ssl: true
  host: callcapture.com

  healthcheck:
    path: /
    interval: 5
    timeout: 10

registry:
  server: registry.hub.docker.com
  username: sgalbur128
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_HOST
    - JAVA_OPTS

  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: enabled
    RAILS_SERVE_STATIC_FILES: enabled
    WEB_CONCURRENCY: 0
    RAILS_MAX_THREADS: 20
    DB_HOST: callcapture-db

builder:
  arch: amd64
  context: "."
  dockerfile: Dockerfile

accessories:
  db:
    image: postgres:15
    host: 107.170.15.86
    port: 5432:5432
    env:
      clear:
        POSTGRES_DB: callcapture_production
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data